// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPKyDozvnEjeh4L8uuUzscerGRn_Ftw2A',
    appId: '1:712856731929:web:1704e233c4e31b31ca4588',
    messagingSenderId: '712856731929',
    projectId: 'myapp-c3b31',
    authDomain: 'myapp-c3b31.firebaseapp.com',
    storageBucket: 'myapp-c3b31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgxSSjB1yJWAdmvZnTezLBBV3RYAZW7Qw',
    appId: '1:712856731929:android:f2740e5fc2af2366ca4588',
    messagingSenderId: '712856731929',
    projectId: 'myapp-c3b31',
    storageBucket: 'myapp-c3b31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdgycsfoGrFHThFsy8kAwtNpRv3CkSa2U',
    appId: '1:712856731929:ios:434bc876ec0c9887ca4588',
    messagingSenderId: '712856731929',
    projectId: 'myapp-c3b31',
    storageBucket: 'myapp-c3b31.appspot.com',
    iosClientId: '712856731929-bhjpm1kvi3q6juerm5doqh4n2mcchjm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
